### ISSUE TITLE
Homebridge accessories not responding

### ISSUE THREAD

**Issue by johnsills1** [bluemaex/homebridge-denon-quickselect#2]
When I add the following to my config.json:
{
      "accessory": "denon-quickselect",
      "name": "AppleTV",
      "quickselect": 2,
      "host": "",
      "zone": 1
    }

my homebridge will no longer function properly. I get the "Not responding" error on all accessories for homebridge.

Here is how my config.json looks like

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "accessories": [
        {
            "accessory": "marantz-volume",
            "name": "DENON",
            "host": "192.168.1.89",
            "maxVolume": 80,
            "controlPower": true
        },
{
      "accessory": "denon-quickselect",
      "name": "AppleTV",
      "quickselect": 1,
      "host": "192.168.1.89",
      "zone": 1
    }
    ],
    "platforms": [
        {
            "platform": "Nest",
            "clientId": "secret",
            "clientSecret": "secret",
            "code": "secret",
            "token": "secret"
        },
        {
            "platform": "homebridge-plex-sensors.Plex",
            "sensors": [
                {
                    "name": "Plex",
                    "types": "movie",
                    "players": "Living Room"
                }
            ]
        }
    ]
}

As soon as I remove the accessory entry for the denon-quickselect, everything starts working again.

**Comment by johnsills1** [comment]
Does the person that created this NOT get an email notification of issues. No response for an entire week, come on dude.

**Comment by bluemaex** [comment]
@johnsills1 Well, this software is provided for free - I do this in my free time, so you are not entitled for getting support instantly for free either. 

Also your "bug report" is very incomplete:
 - What kind of error does homebridge print out on the console if you use this plugin?
 - Did you try starting homebridge in DEBUG mode and see if you get more information there?

**Comment by johnsills1** [comment]
Don’t worry about it. When I do something, even if it’s free, I do the best I can, especially if it’s free.

Waiting weeks to respond let’s me know you really don’t care. So thanks for nothing. Go pat yourself on the back for being less than awesome

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
