### ISSUE TITLE
Accessory not responding

### ISSUE THREAD

**Issue by Partizan7676** [bluemaex/homebridge-denon-quickselect#3]
Hi!
Denon X1400H
quickselect was configured in the Denon App.
Config:
        {
            "accessory": "denon-quickselect",
            "name": "MEDIA PLAYER",
            "quickselect": 3,
            "host": "10.0.3.2",
            "zone": 1
        }
Accessory is appear in HomeApp, but it constantly refreshing and after timeout i get "Not responding" state. So it is not working.
In the logs i get:
when bridge starts i get
[2019-3-19 11:30:22] [MEDIA PLAYER] Initializing denon-quickselect accessory...
after that
[2019-3-19 11:30:44] [MEDIA PLAYER] null

**Comment by Partizan7676** [comment]
please update readme. find solution! for my reciever wich is officially no web-based interface. just add port 8080 to host parameter and it's work!!! example:
        {
            "accessory": "denon-quickselect",
            "name": "MEDIA PLAYER",
            "quickselect": 3,
            "host": "10.0.3.2:8080",
            "zone": 1
        }

**Comment by bluemaex** [comment]
@Partizan7676 Interesting, which model do you have?

**Comment by bluemaex** [comment]
@Partizan7676 Ah, I overread that you use the Denon X1400H. I'll add it to the README - Thanks for your hint 👍
